# vim: ft=sh

# ls aliases and such
#alias ls='ls --color=auto' #For Ubuntu
alias ls='ls -G' #For OSX
alias l=ls
alias s=ls
alias ll='ls -lh'
alias la='ls -alh'
alias lsd='ls -Galh | grep ^d'
alias lf='ls -Glh | grep ^d'
alias gls='gls --color=auto'
alias grep='grep --color=always'

# Convenience
alias bmod='vim ~/.bashrc'
alias bsave='source ~/.bashrc'
alias alt='vim ~/.bash_aliases'
alias bpro='vim ~/.bash_prompt'
alias vmod='vim ~/.vimrc'
alias vi='vim'
alias v='vim'
alias c='clear'
alias cl='clear;ls'
alias ..='cd ..'
alias tmux='tmux -2'
alias racket='racket -il xrepl'
alias tag="ctags && (which coffeetags && coffeetags -R -f .coffeetags || true) && (which ripper-tags && ripper-tags -R --exclude=vendor -f .rippertags)"

# Moving around
alias me='cd ~/;ls'
alias doc='cd ~/Documents/ && ls'
alias dot='cd ~/Documents/dotfiles && ls'
alias si='cd ~/Sites && ls'

# SSH aliases
alias line='ssh villustrator.com'

# Laravel aliases
alias art='php artisan'

# Eclim
alias eclim='~/Downloads/eclipse/eclimd'
