# Variables referencing paths
BLOGPATH=$HOME/Documents/blog/source/_posts
CSHOMEWORK=$HOME/Documents/homework/214/pa6

#ls aliases and such
#alias ls='ls --color=auto' #For Ubuntu
alias ls='ls -G' #For OSX
alias l=ls
alias s=ls
alias ll="ls -lh"
alias la="ls -alh"
alias lsd='ls -Galh | grep ^d'
alias lf='ls -Glh | grep ^d'
alias grep="grep --color=always"

#convenience
alias bmod='vim ~/.bashrc'
alias bsave='source ~/.bashrc'
alias alt='vim ~/.bash_aliases'
alias bpro='vim ~/.bash_prompt'
alias vmod='vim ~/.vimrc'
alias vi='vim'
alias v='vim'
alias c='clear'
alias cl="clear;ls"
alias ..='cd ..'
alias tmux="tmux -2"

#moving around
alias me='cd ~/;ls'
alias doc='cd ~/Documents/;ls'
alias dot='cd ~/Documents/dotfiles;ls'
alias si='cd ~/Sites;ls'
alias cs='cd $CSHOMEWORK;ls'
alias blog='cd $BLOGPATH;tree'
alias gm='cd ~/Documents/game-on/app;ls'

#ssh aliases
alias facade='ssh facade.rutgers.edu'
alias dream='ssh ps61838.dreamhost.com'
alias line='ssh 50.116.63.16'
alias patterns='ssh patterns.rutgers.edu'
alias alpha='ssh alpha.www.cs.rutgers.edu'

#Laravel aliases
alias bob="php artisan bob::build"
alias art="php artisan"
