# If not running interactively, don't do anything
[ -z "$PS1" ] && return


#History settings
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
HISTIGNORE=?:??:???:clear:vmod:bmod:bsave:tmux


#Export statements
export PATH=/usr/local/bin:$PATH:$HOME/.rvm/bin:$HOME/Documents/android/platform-tools:$HOME/Documents/android/tools
export EDITOR=vim
export NDK_CCACHE=/usr/local/bin/ccache
export NUM_CPUS=8
export ANDROID_SDK=/Users/bilalq/Documents/android/


#Source aliases
source $HOME/.bash_aliases

#Source prompt configuration
source $HOME/.bash_prompt


#Bash completion for OSX
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi
